# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "golang.org/x/tools/cmd/goimports",
  "github.com/golang/lint/golint",
  "honnef.co/go/tools/cmd/gosimple",
  "honnef.co/go/tools/cmd/staticcheck",
  "honnef.co/go/tools/cmd/unused",
  "github.com/favclip/qbg"
]

[[constraint]]
  branch = "master"
  name = "github.com/favclip/testerator"

[[constraint]]
  name = "github.com/favclip/ucon"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mjibson/goon"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "master"
  name = "google.golang.org/appengine"
